Repository InnerCircle-ICD3/o2o-fe, pull requests merged in 2025-06, with the labels that each got.

#109 feat: 사용자 location 정보 전역변수로 변경
  apps/user/src/hooks/useAutoComplete/index.ts
  apps/user/src/hooks/useAutoComplete/useAutoComplete.test.ts
  apps/user/src/hooks/useGeolocation/index.ts
  apps/user/src/stores/index.test.ts
  apps/user/src/stores/index.ts
  apps/user/src/stores/searchHistoryStore/index.ts
  apps/user/src/stores/userLocationStore/index.ts
Labels: Needs Review

#114 chore: 지도 검색 api 연동 작업
  apps/user/src/apis/ssr/locations/index.ts
  apps/user/src/components/common/kakaoMap/index.tsx
  apps/user/src/components/common/kakaoMap/kakaoMap.test.tsx
  apps/user/src/components/ui/locations/myLocation/index.tsx
  apps/user/src/components/ui/locations/searchMap/index.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.test.tsx
  apps/user/src/components/ui/locations/storeMapInfo/index.tsx
  apps/user/src/components/ui/locations/storeMapInfo/storeMapInfo.test.tsx
  apps/user/src/mocks/handlers/search/location/index.ts
  apps/user/src/mocks/handlers/stores/index.ts
  apps/user/src/types/searchMap.type.ts
  apps/user/src/utils/locations/locationUtils.test.tsx
  apps/user/src/utils/locations/locationUtils.ts
Labels: Needs Review

#117 chore: Prod용 script 추가
  apps/user/package.json
Labels: Needs Review

#120 feat: 상품 상세 변경된 구조 반영 및 목데이터 인터페이스 수정
  apps/user/public/icons/check_disabled.svg
  apps/user/src/app/(topNav)/stores/[id]/products/page.tsx
  apps/user/src/components/common/checkbox/checkbox.test.tsx
  apps/user/src/components/common/checkbox/index.tsx
  apps/user/src/components/common/products/products.css.ts
  apps/user/src/components/ui/storesDetail/bottomButton/index.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/index.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storesDetail/productSelector/index.tsx
  apps/user/src/components/ui/storesDetail/select/index.tsx
  apps/user/src/components/ui/storesDetail/select/select.css.ts
  apps/user/src/components/ui/storesDetail/select/select.test.tsx
  apps/user/src/components/ui/storesDetail/selectedItem/index.tsx
  apps/user/src/components/ui/storesDetail/storesProducts/index.tsx
  apps/user/src/components/ui/storesDetail/storesProducts/storesProduct.css.ts
  apps/user/src/components/ui/storesDetail/totalPrice/index.tsx
  apps/user/src/components/ui/storesDetail/totalPrice/totalPrice.css.ts
  apps/user/src/hooks/api/usePostOrder/index.ts
  apps/user/src/hooks/useSelectedProducts/index.ts
  apps/user/src/mocks/handlers/search/store/index.ts
  apps/user/src/mocks/handlers/stores/index.ts
  apps/user/src/types/apis/stores.type.ts
  apps/user/src/types/orders.type.ts
Labels: Needs Review

#125 feat: 자주 묻는 질문
  apps/user/src/app/(topNav)/mypage/faq/[id]/page.tsx
  apps/user/src/app/(topNav)/mypage/faq/page.tsx
  apps/user/src/app/(topNav)/mypage/notice/[id]/page.tsx
  apps/user/src/app/(topNav)/mypage/notice/page.test.tsx
  apps/user/src/app/(topNav)/mypage/notice/page.tsx
  apps/user/src/components/ui/layout/topNav/index.tsx
  apps/user/src/components/ui/layout/topNav/topNav.test.tsx
  apps/user/src/components/ui/mypage/infoDetail/index.tsx
  apps/user/src/components/ui/mypage/infoDetail/infoDetail.css.ts
  apps/user/src/components/ui/mypage/infoItem/index.tsx
  apps/user/src/components/ui/mypage/infoItem/infoItem.css.ts
  apps/user/src/components/ui/mypage/infoItem/infoItem.test.tsx
  apps/user/src/components/ui/mypage/infoList/index.tsx
  apps/user/src/components/ui/mypage/infoList/infoList.css.ts
  apps/user/src/components/ui/notice/noticeItem/index.tsx
  apps/user/src/constants/route/index.tsx
  apps/user/src/types/apis/mypage.type.ts
  apps/user/src/types/apis/notice.type.ts
Labels: Needs Review

#132 fix: mypage 로그인 정보에 따른 필터링
  apps/user/src/app/(bottomNav)/mypage/page.tsx
Labels: Needs Review

#119 상품관리 init: product-management UI
  apps/owner/package.json
  apps/owner/src/apis/ssr/file-upload/index.ts
  apps/owner/src/apis/ssr/product/index.ts
  apps/owner/src/app/layout.tsx
  apps/owner/src/app/product-management/[id]/page.tsx
  apps/owner/src/app/product-management/new/page.tsx
  apps/owner/src/app/product-management/page.tsx
  apps/owner/src/components/common/header.tsx
  apps/owner/src/components/common/layout-content.tsx
  apps/owner/src/components/common/sidebar.tsx
  apps/owner/src/components/ui/card.tsx
  apps/owner/src/components/ui/pagination.tsx
  apps/owner/src/components/ui/slider.tsx
  apps/owner/src/components/ui/table.tsx
  apps/owner/src/components/ui/toggle-group.tsx
  apps/owner/src/components/ui/toggle.tsx
  apps/owner/src/constants/product.ts
  apps/owner/src/types/file-upload.ts
  apps/owner/src/types/product.ts
  apps/user/src/app/(bottomNav)/my-orders/page.test.tsx
  apps/user/src/app/(bottomNav)/my-orders/page.tsx
  pnpm-lock.yaml
Labels: Needs Review

#124 Feat: 유저 로그인 이후 추가 정보 입력
  apps/user/src/app/(topNav)/mypage/complete-profile/complete-profile.css.ts
  apps/user/src/app/(topNav)/mypage/complete-profile/page.tsx
  apps/user/src/components/ui/mypage/completeProfile/completeProfile.css.ts
  apps/user/src/components/ui/mypage/completeProfile/completeProfile.test.tsx
  apps/user/src/components/ui/mypage/completeProfile/index.tsx
  apps/user/src/providers/userInfo/index.tsx
Labels: Needs Review

#141 feat: 주문 내역 api 연동
  apps/user/src/app/(bottomNav)/my-orders/page.tsx
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/components/common/errorUi/index.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/ui/my-orders/actionButtons/actionButton.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/orderItem.css.ts
  apps/user/src/components/ui/my-orders/orderItem/orderItem.test.tsx
  apps/user/src/constants/my-orders/index.ts
  apps/user/src/hooks/api/useGetMyOrder/index.ts
  apps/user/src/styles/theme.css.ts
  apps/user/src/types/apis/order.type.ts
  biome.json
Labels: Needs Review

#144 feat: 메인페이지 API 연동
  apps/user/public/images/22a67353-20eb-4821-b74c-0a025b1ff14b.png
  apps/user/public/images/eac9c08b-56bd-4ac3-b0d0-a329f5d6265e.png
  apps/user/src/apis/ssr/stores/index.ts
  apps/user/src/app/(bottomNav)/page.css.ts
  apps/user/src/app/(bottomNav)/page.tsx
  apps/user/src/components/common/errorUi/errorUi.css.ts
  apps/user/src/components/common/errorUi/index.tsx
  apps/user/src/components/common/storeInfo/index.tsx
  apps/user/src/components/ui/filterTab/constant.ts
  apps/user/src/components/ui/filterTab/filterTab.css.ts
  apps/user/src/components/ui/filterTab/foodTypeFilter.tsx
  apps/user/src/components/ui/filterTab/index.tsx
  apps/user/src/components/ui/filterTab/pickUpTimeFilter.tsx
  apps/user/src/components/ui/filterTab/type.ts
  apps/user/src/components/ui/filterTab/utils.ts
  apps/user/src/components/ui/mainHeader/index.tsx
  apps/user/src/components/ui/mainHeader/locationFilter.tsx
  apps/user/src/components/ui/mainHeader/mainHeader.css.ts
  apps/user/src/components/ui/storeList/storeCard/storeCard.css.ts
  apps/user/src/components/ui/storeList/storeListContainer/index.tsx
  apps/user/src/components/ui/storeList/storeListContainer/storeListContainer.css.ts
  apps/user/src/hooks/api/useStoreList/index.ts
  apps/user/src/hooks/useGeolocation/index.ts
  apps/user/src/types/apis/stores.type.ts
  apps/user/src/utils/format/index.ts
  apps/user/src/utils/virtualScroll/index.ts
Labels: Needs Review

#137 Feat: 매장 정보 수정 및 영업 상태 수정
  apps/owner/next.config.ts
  apps/owner/package.json
  apps/owner/src/apis/client.ts
  apps/owner/src/apis/ssr/file-upload/index.ts
  apps/owner/src/apis/ssr/store/index.ts
  apps/owner/src/apis/ssr/stores/index.ts
  apps/owner/src/app/store-management/edit/page.tsx
  apps/owner/src/components/common/formField/formField.test.tsx
  apps/owner/src/components/common/formField/index.tsx
  apps/owner/src/components/common/multipleSelect/index.tsx
  apps/owner/src/components/common/multipleSelect/multipleSelect.test.tsx
  apps/owner/src/components/common/sidebar.tsx
  apps/owner/src/components/common/stepper/index.tsx
  apps/owner/src/components/common/stepper/stepper.test.tsx
  apps/owner/src/components/common/tagInput/index.tsx
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/owner/src/components/store/edit/index.tsx
  apps/owner/src/components/store/register/businessHoursSection/businessHourSection.test.tsx
  apps/owner/src/components/store/register/businessHoursSection/index.tsx
  apps/owner/src/components/store/register/index.tsx
  apps/owner/src/components/store/register/register.test.tsx
  apps/owner/src/components/ui/switch.tsx
  apps/owner/src/constants/store.ts
  apps/owner/src/hooks/api/useGetOwnerStore/index.ts
  apps/owner/src/hooks/api/usePatchOwnerStoreStatus/index.ts
  apps/owner/src/hooks/api/usePostFileUpload/index.ts
  apps/owner/src/hooks/api/usePostOwnerStore/index.ts
  apps/owner/src/hooks/api/usePutOwnerStore/index.ts
  apps/owner/src/hooks/api/utils/useMutation/index.ts
  apps/owner/src/hooks/api/utils/useQuery/index.ts
  apps/owner/src/hooks/useAddressToCoordinates/index.ts
  apps/owner/src/hooks/useBusinessHours/index.ts
  apps/owner/src/hooks/useBusinessHours/useBusinessHours.test.ts
  apps/owner/src/hooks/useDaumPostcode/useDaumPostcode.test.ts
  apps/owner/src/hooks/useStoreAddress/index.ts
  apps/owner/src/hooks/useStoreAddress/useStoreAddress.test.ts
  apps/owner/src/lib/jwt.ts
  apps/owner/src/providers/ownerInfo/index.tsx
  apps/owner/src/stores/ownerInfoStore/index.ts
  apps/owner/src/types/store.ts
  apps/owner/src/utils/stores/index.ts
  apps/owner/src/utils/stores/stores.test.ts
  apps/user/src/apis/client.ts
  apps/user/src/app/(topNav)/search/page.test.tsx
  apps/user/src/components/common/kakaoMap/kakaoMap.test.tsx
  apps/user/src/components/ui/locations/myLocation/myLocation.test.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.test.tsx
  apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.css.ts
  apps/user/src/hooks/useSelectedProducts/useSelectedProducts.test.ts
  apps/user/src/utils/locations/index.ts
  apps/user/src/utils/locations/locationUtils.test.tsx
  pnpm-lock.yaml
Labels: Needs Review

#147 feat: 카테고리 UI 추가
  apps/user/public/images/all.png
  apps/user/public/images/banner.png
  apps/user/public/images/banner2.png
  apps/user/public/images/banner3.png
  apps/user/public/images/bread.png
  apps/user/public/images/cafe.png
  apps/user/public/images/fruit.png
  apps/user/public/images/home.png
  apps/user/public/images/korean.png
  apps/user/public/images/my-order.png
  apps/user/public/images/pizza.png
  apps/user/public/images/ricecake.png
  apps/user/public/images/salad.png
  apps/user/public/images/sandwich.png
  apps/user/public/images/subscribe-error.png
  apps/user/public/images/subscribe.png
  apps/user/src/components/common/errorUi/index.tsx
  apps/user/src/components/common/virtualScroll/index.tsx
  apps/user/src/components/ui/filterTab/constant.ts
  apps/user/src/components/ui/filterTab/pickUpTimeFilter.tsx
  apps/user/src/components/ui/storeList/categories/categories.css.ts
  apps/user/src/components/ui/storeList/categories/index.tsx
  apps/user/src/components/ui/storeList/storeListContainer/index.tsx
Labels: Needs Review

#162 fix/owner api 설정 수정 (product 쪽만 baseUrl이 달라서 그에 맞게 처리함)
  apps/owner/src/apis/client.ts
  apps/owner/src/apis/ssr/file-upload/index.ts
  apps/owner/src/apis/ssr/product/index.ts
  apps/owner/src/apis/ssr/review/index.ts
  apps/owner/src/apis/ssr/stores/index.ts
Labels: Needs Review

#159 feat/owner: 주문 전역상태 모달 추가 및 SSE 작업
  apps/owner/src/__test__/page.test.tsx
  apps/owner/src/app/layout.tsx
  apps/owner/src/app/page.tsx
  apps/owner/src/components/common/order-alert-modal.tsx
  apps/owner/src/components/common/order-sse-listener-wrapper.tsx
  apps/owner/src/components/common/order-sse-listener.tsx
  apps/owner/src/components/common/sse-status-indicator.tsx
  apps/owner/src/components/common/sse-test-panel.tsx
  apps/owner/src/mocks/handlers/example/index.ts
  apps/owner/src/mocks/handlers/index.ts
  apps/owner/src/mocks/handlers/sse/index.ts
  apps/owner/src/mocks/utils.ts
  apps/owner/src/stores/orderModalStore.ts
  apps/owner/src/types/order.ts
Labels: Needs Review

#156 Refactor: 점주 등록, 수정 UX 개선
  apps/owner/src/apis/ssr/stores/index.ts
  apps/owner/src/app/page.tsx
  apps/owner/src/components/common/formField/index.tsx
  apps/owner/src/components/common/toastMessage/index.tsx
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/owner/src/components/store/edit/index.tsx
  apps/owner/src/components/store/register/index.tsx
  apps/owner/src/constants/store.ts
  apps/owner/src/hooks/api/usePatchOwnerStoreStatus/index.ts
  apps/owner/src/hooks/api/usePostOwnerStore/index.ts
  apps/owner/src/hooks/api/usePutOwnerStore/index.ts
  apps/owner/src/hooks/useToastMessage/index.ts
  apps/owner/src/utils/stores/index.ts
Labels: Needs Review

#166 fix: product api instance deprecated
  apps/owner/src/apis/client.ts
  apps/owner/src/apis/ssr/product/index.ts
Labels: Needs Review

#157 Refactor: 동네 인증 UX 수정
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/user/next.config.ts
  apps/user/public/icons/reload.svg
  apps/user/src/apis/ssr/customer/index.ts
  apps/user/src/app/(bottomNav)/mypage/mypage.test.tsx
  apps/user/src/app/(bottomNav)/mypage/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/toastMessage/index.tsx
  apps/user/src/components/common/toastMessage/toastMessage.css.ts
  apps/user/src/components/ui/locations/addressSelector/index.tsx
  apps/user/src/components/ui/locations/myLocation/index.tsx
  apps/user/src/components/ui/locations/searchMap/index.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.css.ts
  apps/user/src/components/ui/locations/storeMapInfo/index.tsx
  apps/user/src/components/ui/locations/storeMapInfo/storeMapInfo.css.ts
  apps/user/src/components/ui/locations/storeMapInfo/storeMapInfo.test.tsx
  apps/user/src/constants/locations/index.ts
  apps/user/src/hooks/api/usePostLogout/index.ts
  apps/user/src/stores/toastStore/index.ts
  apps/user/src/utils/locations/index.ts
Labels: Needs Review

#167 feat: 유저 주문내역 리뷰작성 및 조회
  apps/user/public/icons/camera.svg
  apps/user/public/icons/star-empty.svg
  apps/user/src/apis/ssr/image-upload/index.ts
  apps/user/src/apis/ssr/review/index.ts
  apps/user/src/app/(topNav)/review/[id]/page.css.ts
  apps/user/src/app/(topNav)/review/[id]/page.tsx
  apps/user/src/app/(topNav)/review/register/constants.ts
  apps/user/src/app/(topNav)/review/register/page.css.ts
  apps/user/src/app/(topNav)/review/register/page.tsx
  apps/user/src/components/common/storeInfo/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/orderItem.test.tsx
  apps/user/src/components/ui/review/content.css.ts
  apps/user/src/components/ui/review/content.tsx
  apps/user/src/components/ui/review/images.css.ts
  apps/user/src/components/ui/review/images.tsx
  apps/user/src/components/ui/review/rating.css.ts
  apps/user/src/components/ui/review/rating.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/index.tsx
  apps/user/src/constants/route/index.tsx
Labels: WIP

#163 Feat: 매장 위치 지도 보기
  apps/user/src/app/(topNav)/locations/store-location/page.tsx
  apps/user/src/components/ui/locations/storeMap/index.tsx
  apps/user/src/components/ui/locations/storeMap/storeMap.css.ts
  apps/user/src/constants/route/index.tsx
Labels: Needs Review

#168 fix: 비로그인시 sse 연결 시도를 하지 않음
  apps/owner/src/components/common/order-sse-listener.tsx
  apps/owner/src/components/common/sse-status-indicator.tsx
Labels: Needs Review

#173 fix: list api 수정
  apps/user/public/images/loading.png
  apps/user/src/apis/ssr/locations/index.ts
  apps/user/src/app/(bottomNav)/my-orders/page.tsx
  apps/user/src/app/(bottomNav)/subscribes/page.tsx
  apps/user/src/app/(bottomNav)/subscribes/subscribes.css.ts
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/virtualScroll/index.tsx
  apps/user/src/components/ui/filterTab/foodTypeFilter.tsx
  apps/user/src/components/ui/filterTab/pickUpTimeFilter.tsx
  apps/user/src/components/ui/mainHeader/index.tsx
  apps/user/src/components/ui/mainHeader/locationFilter.tsx
  apps/user/src/components/ui/storeList/categories/categories.css.ts
  apps/user/src/components/ui/storeList/categories/index.tsx
  apps/user/src/components/ui/storeList/storeListContainer/index.tsx
  apps/user/src/components/ui/subscribe/subscribeItem/index.tsx
  apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.css.ts
  apps/user/src/hooks/api/useAddressList/index.tsx
  apps/user/src/hooks/api/useStoreList/index.ts
  apps/user/src/providers/index.tsx
  apps/user/src/providers/userInfo/index.tsx
  apps/user/src/providers/userInfo/userInfo.css.ts
  apps/user/src/stores/useFilterTab/index.ts
  apps/user/src/stores/userLocationStore/index.ts
Labels: Needs Review

#178 운영자 상품 - api 수정 및 s3 uploader 코드 개선
  apps/owner/package.json
  apps/owner/src/app/product-management/[id]/page.tsx
  apps/owner/src/app/product-management/new/page.tsx
  apps/owner/src/app/product-management/page.tsx
  apps/owner/src/types/file-upload.ts
  apps/owner/src/types/product.ts
  pnpm-lock.yaml
Labels: Needs Review

#181 fix: products csr로 변경
  apps/user/next.config.ts
  apps/user/src/app/(topNav)/stores/[id]/products/page.tsx
Labels: Needs Review, WIP

#172 chore: 작업 플로우 점검
  apps/owner/public/images/kakao_icon.svg
  apps/owner/src/apis/ssr/stores/index.ts
  apps/owner/src/app/api/me/route.ts
  apps/owner/src/app/pickup-management/page.tsx
  apps/owner/src/components/common/formField/index.tsx
  apps/owner/src/components/common/multipleSelect/index.tsx
  apps/owner/src/components/common/multipleSelect/multipleSelect.test.tsx
  apps/owner/src/components/common/order-alert-modal.tsx
  apps/owner/src/components/common/tagInput/index.tsx
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/owner/src/components/store/edit/index.tsx
  apps/owner/src/components/store/login/index.tsx
  apps/owner/src/components/store/register/businessHoursSection/businessHourSection.test.tsx
  apps/owner/src/components/store/register/businessHoursSection/index.tsx
  apps/owner/src/components/store/register/index.tsx
  apps/owner/src/components/store/register/register.test.tsx
  apps/owner/src/components/ui/button.tsx
  apps/owner/src/components/ui/input.tsx
  apps/owner/src/constants/store.ts
  apps/owner/src/hooks/api/useGetOwnerStore/index.ts
  apps/owner/src/hooks/api/usePatchOwnerStoreStatus/index.ts
  apps/owner/src/hooks/api/usePostOwnerStore/index.ts
  apps/owner/src/hooks/api/usePutOwnerStore/index.ts
  apps/owner/src/lib/jwt.ts
  apps/owner/src/providers/ownerInfo/index.tsx
  apps/owner/src/stores/ownerInfoStore/index.ts
  apps/user/src/apis/ownerClient.ts
  apps/user/src/apis/ssr/customers/index.ts
  apps/user/src/apis/ssr/locations/index.ts
  apps/user/src/app/(bottomNav)/mypage/mypage.test.tsx
  apps/user/src/app/(bottomNav)/mypage/page.tsx
  apps/user/src/app/api/me/route.ts
  apps/user/src/components/ui/locations/addressSearch/index.tsx
  apps/user/src/components/ui/locations/searchMap/index.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.test.tsx
  apps/user/src/components/ui/login/index.tsx
  apps/user/src/components/ui/mypage/completeProfile/completeProfile.test.tsx
  apps/user/src/components/ui/mypage/completeProfile/index.tsx
  apps/user/src/components/ui/mypage/loginLink/index.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/index.tsx
  apps/user/src/hooks/api/useGetCustomer/index.ts
  apps/user/src/hooks/useGeolocation/index.ts
  apps/user/src/mocks/handlers/search/location/index.ts
  apps/user/src/mocks/handlers/search/store/index.ts
  apps/user/src/mocks/handlers/stores/index.ts
  apps/user/src/stores/userLocationStore/index.ts
  apps/user/src/types/locations.type.ts
  apps/user/src/utils/locations/index.ts
  apps/user/src/utils/locations/locationUtils.test.tsx
  packages/constants/login.ts
Labels: Needs Review

#182 Feat/pull to refresh2
  apps/user/src/app/(bottomNav)/page.tsx
  apps/user/src/app/(topNav)/search/page.tsx
  apps/user/src/components/ui/pullToRefresh/index.tsx
  apps/user/src/components/ui/pullToRefresh/pullToRefresh.css.ts
  apps/user/src/components/ui/pullToRefresh/pullToRefresh.tsx
  apps/user/src/styles/theme.css.ts
Labels: WIP

#184 feat: loading
  apps/user/src/hooks/api/useGetMyOrder/index.ts
  apps/user/src/hooks/api/useStoreList/index.ts
  apps/user/src/hooks/api/useSubscribeList/index.ts
  apps/user/src/hooks/useLoading/index.ts
Labels: Needs Review

#185 feat: meta favicon title...
  apps/user/src/app/favicon.ico
  apps/user/src/app/layout.tsx
Labels: Needs Review

#174 Feat: 점주, 고객 계정 삭제 및 매장 삭제
  apps/owner/src/apis/ssr/store-owner/index.ts
  apps/owner/src/apis/ssr/stores/index.ts
  apps/owner/src/app/api/me/route.ts
  apps/owner/src/app/mypage/page.tsx
  apps/owner/src/app/not-found.tsx
  apps/owner/src/app/page.tsx
  apps/owner/src/app/reviews/page.tsx
  apps/owner/src/app/store-management/delete/page.tsx
  apps/owner/src/app/store-management/edit/page.tsx
  apps/owner/src/app/store-owner/delete/page.tsx
  apps/owner/src/components/common/header.tsx
  apps/owner/src/components/common/layout-content.tsx
  apps/owner/src/components/common/order-alert-modal.tsx
  apps/owner/src/components/common/sidebar.tsx
  apps/owner/src/components/common/storeRegisterLink/index.tsx
  apps/owner/src/components/store/delete/index.tsx
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/owner/src/components/store/edit/index.tsx
  apps/owner/src/components/store/register/index.tsx
  apps/owner/src/components/storeOwner/delete/index.tsx
  apps/owner/src/constants/notice.ts
  apps/owner/src/hooks/api/usePostLogout/index.ts
  apps/owner/src/providers/ownerInfo/index.tsx
  apps/user/src/apis/ssr/account/index.ts
  apps/user/src/apis/ssr/customers/index.ts
  apps/user/src/app/(bottomNav)/mypage/page.tsx
  apps/user/src/app/(topNav)/mypage/delete-account/delete-account.css.ts
  apps/user/src/app/(topNav)/mypage/delete-account/page.tsx
  apps/user/src/app/api/me/route.ts
  apps/user/src/components/common/button/button.css.ts
  apps/user/src/components/ui/locations/searchMap/index.tsx
  apps/user/src/components/ui/mypage/deleteAccount/deleteAccount.css.ts
  apps/user/src/components/ui/mypage/deleteAccount/index.tsx
  apps/user/src/constants/route/index.tsx
  apps/user/src/hooks/api/useGetCustomer/index.ts
  apps/user/src/hooks/api/usePostLogout/index.ts
  apps/user/src/middleware.ts
  apps/user/src/styles/theme.css.ts
Labels: Needs Review

#186 Fix/owner product review 하드코딩 제거
  apps/owner/src/app/product-management/[id]/page.tsx
  apps/owner/src/app/product-management/new/page.tsx
  apps/owner/src/app/product-management/page.tsx
  apps/owner/src/app/reviews/page.tsx
  apps/owner/src/utils/imageUpload.ts
  biome.json
Labels: Needs Review

#189 chore: 테스트코드 작성
  apps/owner/src/app/reviews/page.tsx
  apps/owner/src/app/store-management/delete/store-managemnet-delete.test.tsx
  apps/owner/src/app/store-management/edit/store-managemnet-edit.test.tsx
  apps/owner/src/app/store-owner/delete/store-owner-delete.test.tsx
  apps/owner/src/app/store/login/store-login.test.tsx
  apps/owner/src/app/store/register/store-register.test.tsx
  apps/owner/src/components/common/storeRegisterLink/index.tsx
  apps/owner/src/components/common/storeRegisterLink/storeRegisterLink.test.tsx
  apps/owner/src/components/common/toastMessage/toastMessage.test.tsx
  apps/owner/src/components/store/delete/delete.test.tsx
  apps/owner/src/components/storeOwner/delete/delete.test.tsx
  apps/owner/src/hooks/useToastMessage/useToastMessage.test.ts
  apps/owner/src/middleware.test.ts
  apps/user/src/app/(bottomNav)/locations/search/locations-search.test.tsx
  apps/user/src/app/(bottomNav)/mypage/page.tsx
  apps/user/src/app/(topNav)/locations/address-search/address-search.test.tsx
  apps/user/src/app/(topNav)/locations/address-search/page.tsx
  apps/user/src/app/(topNav)/locations/my-location/my-location.test.tsx
  apps/user/src/app/(topNav)/locations/store-location/store-location.test.tsx
  apps/user/src/app/(topNav)/login/login.test.tsx
  apps/user/src/app/(topNav)/mypage/complete-profile/complete-profile.test.tsx
  apps/user/src/app/(topNav)/mypage/delete-account/delete-account.test.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/common/toastMessage/index.tsx
  apps/user/src/components/common/toastMessage/toastMessage.test.tsx
  apps/user/src/components/ui/locations/addressSearch/addressSearch.test.tsx
  apps/user/src/components/ui/locations/addressSearch/index.tsx
  apps/user/src/components/ui/locations/addressSelector/index.tsx
  apps/user/src/components/ui/locations/loadingMap/loadingMap.test.tsx
  apps/user/src/components/ui/locations/myLocation/index.tsx
  apps/user/src/components/ui/locations/storeMap/storeMap.test.tsx
  apps/user/src/components/ui/mypage/completeProfile/completeProfile.test.tsx
  apps/user/src/components/ui/mypage/completeProfile/index.tsx
  apps/user/src/components/ui/mypage/deleteAccount/deleteAccount.test.tsx
  apps/user/src/components/ui/orders/reserve/index.tsx
  apps/user/src/hooks/useKakaoAddressSearch/useKakaoAddressSearch.test.ts
  apps/user/src/hooks/useKakaoLoader/useKakaoLoader.test.ts
  apps/user/src/middleware.test.ts
  apps/user/src/stores/useToastStore/index.ts
  apps/user/src/stores/useToastStore/useToastStore.test.ts
  apps/user/src/stores/userLocationStore/useLocationStore.test.ts
  apps/user/src/utils/locations/index.ts
  vitest.config.ts
Labels: Needs Review

#196 fix: 디테일 수정
  apps/user/src/app/(bottomNav)/subscribes/page.tsx
  apps/user/src/app/orders/[id]/success/page.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/ui/storeList/storeCard/index.tsx
  apps/user/src/components/ui/storeList/storeListContainer/index.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/index.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/storesInfo.css.ts
  apps/user/src/components/ui/subscribe/subscribeItem/index.tsx
  apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.test.tsx
  apps/user/src/hooks/useGeolocation/index.ts
  apps/user/src/hooks/useGeolocation/useGeolocation.test.ts
Labels: Needs Review

#201 Fix/star
  apps/user/src/app/(topNav)/review/[id]/page.tsx
  apps/user/src/components/ui/locations/myLocation/index.tsx
  apps/user/src/components/ui/locations/rangeSelector/rangeSelector.test.tsx
  apps/user/src/components/ui/review/rating.tsx
Labels: WIP

#200 fix: 상품 이미지 수정
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/common/products/index.tsx
  apps/user/src/components/common/products/products.css.ts
Labels: Needs Review

#204 2025-06-20 dev > main 7차
  apps/user/src/components/ui/my-orders/orderItem/index.tsx
Labels: WIP

#205 fix: sse 패널개발환경에서만 보임
  apps/owner/src/app/layout.tsx
Labels: Needs Review

#209 fix: 주문 시 totalPrice 수량 포함 계산
  apps/user/src/components/common/orderInfo/index.tsx
Labels: Needs Review

#211 fix: pickup list
  apps/owner/src/app/pickup-management/page.tsx
  apps/owner/src/components/common/order-alert-modal.tsx
  apps/owner/src/types/order.ts
Labels: WIP

#213 fix: pickup list
  apps/owner/src/components/common/sse-panel-wrapper.tsx
Labels: WIP

#215 fix: orderItems naming 찐막
  apps/owner/src/components/common/sse-test-panel.tsx
  apps/owner/src/mocks/handlers/sse/index.ts
Labels: WIP

#219 fix: 도메인 수정..
  apps/owner/src/components/common/order-sse-listener.tsx
Labels: Needs Review

#226 fix: pickup filter 리셋
  apps/user/src/components/ui/filterTab/pickUpTimeFilter/index.tsx
Labels: Needs Review

#228 fix: subscribe 새로고침 시 갱신되는 이슈
  apps/user/src/hooks/api/useProduct/index.ts
Labels: Needs Review

#232 chore: 매장 재고 파악 후 영업 상태 변경 제한
  apps/owner/src/components/store/edit/edit.test.tsx
  apps/owner/src/components/store/edit/index.tsx
Labels: Needs Review

#233 fix: order flow
  apps/user/src/components/ui/my-orders/actionButtons/actionButton.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/index.tsx
  apps/user/src/components/ui/orders/reserve/reserve.test.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/index.tsx
  apps/user/src/hooks/api/usePostOrder/index.ts
  packages/errors/base/BaseError.ts
Labels: Needs Review

#234 Fix/owner product management
  apps/owner/src/app/product-management/[id]/page.tsx
  apps/owner/src/app/reviews/page.tsx
  apps/owner/src/components/ui/slider.tsx
  biome.json
Labels: WIP

#236 fix: order
  apps/user/src/apis/types/index.ts
  apps/user/src/apis/utils/result/index.ts
  apps/user/src/components/ui/mypage/completeProfile/completeProfile.test.tsx
  apps/user/src/components/ui/mypage/loginLink/loginLink.test.tsx
  apps/user/src/components/ui/orders/reserve/reserve.test.tsx
  apps/user/src/hooks/api/usePostOrder/index.ts
  packages/errors/base/BaseError.ts
Labels: WIP

#238 fix: order
  apps/user/src/apis/utils/result/index.ts
Labels: WIP

#261 Fix/order
  apps/user/src/apis/utils/result/index.ts
  packages/errors/base/BaseError.ts
  packages/errors/order/OrderError.ts
  packages/errors/utils/errorRegistry.ts
Labels: WIP

#269 chore: 에러 메세지 오류 수정
  apps/owner/src/apis/utils/result/index.ts
  apps/owner/src/app/page.tsx
  apps/owner/src/components/store/register/index.tsx
  packages/errors/store/StoreError.ts
  packages/errors/utils/errorRegistry.ts
Labels: Needs Review, WIP
