Repository InnerCircle-ICD3/o2o-fe, pull requests merged in 2025-05, with the labels that each got.

#7 chore: 자동화 설정
  .github/scripts/assign-reviewer.ts
  .github/workflows/pr-init.yml
  .github/workflows/review-on-label.yml
  package-lock.json
  package.json
  tsconfig.actions.json
Labels: Needs Review

#3 chore: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs Review

#4 chore: biome
  .env.example
  .gitignore
  biome.json
  package-lock.json
  package.json
  src/app/components/sample/Counter.tsx
  src/app/components/sample/TodoList.tsx
  src/app/hooks/useTodos.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers/QueryProvider.tsx
  src/app/providers/index.tsx
  src/app/services/client.ts
  src/app/stores/counter/counterStore.ts
  src/app/stores/index.ts
  src/hooks/useTodos.ts
  src/providers/QueryProvider.tsx
  src/providers/index.tsx
  src/services/client.ts
  src/stores/counter/counterStore.ts
  src/stores/index.ts
Labels: Needs Review

#8 chore: vanila-extract/css
  next.config.ts
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.css.ts
  src/app/page.module.css
  src/app/page.tsx
Labels: Needs Review

#37 chore: package.json 중복제거
  package-lock.json
  package.json
Labels: Needs Review, WIP

#13 chore: husky 설정
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/components/sample/Counter.tsx
  src/app/components/sample/TodoList.tsx
  src/app/hooks/useTodos.ts
  src/app/page.tsx
  src/app/providers/QueryProvider.tsx
  src/app/providers/index.tsx
  src/hooks/useTodos.ts
Labels: Needs Review

#38 Chore/vitest v2
  next.config.ts
  package-lock.json
  package.json
  src/__test__/page.test.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.css.ts
  src/app/page.module.css
  src/app/page.tsx
  src/test/setup.ts
  vitest.config.mts
Labels: Needs Review

#40 chore: msw 기본 설정
  .github/scripts/assign-reviewer.ts
  next.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/__test__/page.test.tsx
  src/apis/client.ts
  src/app/hooks/useTodos.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers/index.tsx
  src/app/services/client.ts
  src/app/stores/counter/counterStore.ts
  src/app/stores/index.ts
  src/components/sample/Counter.tsx
  src/components/sample/TodoList.tsx
  src/hooks/useTodos.ts
  src/mocks/browser.ts
  src/mocks/handlers/example/index.ts
  src/mocks/handlers/index.ts
  src/mocks/server.ts
  src/mocks/utils.ts
  src/providers/QueryProvider.tsx
  src/providers/index.tsx
  src/providers/msw/index.tsx
  src/providers/tanstackQuery/index.tsx
  tsconfig.actions.json
Labels: Needs Review

#44 fix: monorepo vitest 설정
  README.md
  apps/user/package.json
  package.json
Labels: Needs Review

#45 chore: 모노레포 ci/cd 구성
  .github/workflows/monorepo-ci.yml
  .github/workflows/owner-ci-cd.yml
  .github/workflows/user-ci-cd.yml
  .gitignore
  README.md
  apps/owner/next.config.ts
  apps/owner/package.json
  apps/owner/vitest.config.mts
  apps/user/next.config.ts
  apps/user/package.json
  apps/user/vitest.config.mts
  package.json
  pnpm-lock.yaml
Labels: Needs Review

#47 fix: slack self dm시 오류 수정
  .github/scripts/assign-reviewer.ts
Labels: Needs Review

#53 fix: husky 설정 변경
  .husky/pre-commit
Labels: Needs Review

#46 feat: 가상 스크롤
  apps/user/src/components/common/virtualScroll/index.tsx
  apps/user/src/components/common/virtualScroll/virtualScroll.test.tsx
  apps/user/src/types/virtualScroll.type.ts
  apps/user/src/utils/virtualScroll/index.ts
  apps/user/src/utils/virtualScroll/virtualScroll.test.ts
Labels: Needs Review

#55 feat: global style 세팅
  apps/user/src/app/layout.tsx
  apps/user/src/styles/reset.css.ts
  apps/user/src/styles/theme.css.ts
Labels: Needs Review

#50 feat: 검색어 상태 + 추천어 관리 + 필터링
  apps/user/src/__test__/hooks/useSearchRecommendations.test.ts
  apps/user/src/hooks/useSearchRecommendations.ts
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/mocks/handlers/recommendations/index.ts
Labels: Needs Review

#54 feat: 공통 컴포넌트 구현
  README.md
  apps/user/public/icons/btn_close.svg
  apps/user/public/icons/check_off.svg
  apps/user/public/icons/check_on.svg
  apps/user/public/icons/subscribe_off.svg
  apps/user/public/icons/subscribe_on.svg
  apps/user/src/app/(not-used)/common-ui/page.css.ts
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/bottomSheet/bottomSheet.css.ts
  apps/user/src/components/common/bottomSheet/bottomSheet.test.tsx
  apps/user/src/components/common/bottomSheet/index.tsx
  apps/user/src/components/common/button/button.css.ts
  apps/user/src/components/common/button/button.test.tsx
  apps/user/src/components/common/button/index.tsx
  apps/user/src/components/common/checkbox/checkbox.css.ts
  apps/user/src/components/common/checkbox/checkbox.test.tsx
  apps/user/src/components/common/checkbox/index.tsx
  apps/user/src/components/common/statusLabel/index.tsx
  apps/user/src/components/common/statusLabel/statusLabel.css.ts
  apps/user/src/components/common/statusLabel/statusLabel.test.tsx
  apps/user/src/styles/theme.css.ts
  apps/user/tsconfig.json
  apps/user/vitest.config.mts
Labels: Needs Review

#57 chore: virtual scroll 개선
  apps/user/package.json
  apps/user/src/components/common/virtualScroll/index.tsx
  apps/user/src/components/common/virtualScroll/virtualScroll.css.ts
  apps/user/src/components/common/virtualScroll/virtualScroll.test.tsx
  apps/user/src/hooks/useSearchRecommendations.ts
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/styles/theme.css.ts
  apps/user/src/types/virtualScroll.type.ts
  pnpm-lock.yaml
Labels: Needs Review

#61 feat: layout 구현
  README.md
  apps/user/public/icons/home.svg
  apps/user/public/icons/location.svg
  apps/user/public/icons/mypage.svg
  apps/user/public/icons/order.svg
  apps/user/public/icons/subscribe.svg
  apps/user/src/__test__/page.test.tsx
  apps/user/src/app/(bottomNav)/layout.tsx
  apps/user/src/app/(bottomNav)/page.css.ts
  apps/user/src/app/(bottomNav)/page.tsx
  apps/user/src/app/layout.css.ts
  apps/user/src/app/layout.tsx
  apps/user/src/components/ui/layout/bottomNav/bottomNav.css.ts
  apps/user/src/components/ui/layout/bottomNav/bottomNav.test.tsx
  apps/user/src/components/ui/layout/bottomNav/index.tsx
  apps/user/src/styles/reset.css.ts
  apps/user/src/styles/theme.css.ts
Labels: Needs Review

#69 chore: add husky scripts for pre-commit setup
  .gitignore
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/styles/theme.css.ts
  package.json
Labels: WIP

#70 feat: add PR template cleanup workflow
  .github/workflows/pr-template-cleanup.yml
Labels: Needs Review

#71 feat: input 공통 컴포넌트
  apps/user/package.json
  apps/user/src/app/(bottomNav)/page.tsx
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/assets/icon/ic-eat.png
  apps/user/src/assets/icon/ic-search.png
  apps/user/src/components/common/textInput/index.tsx
  apps/user/src/components/common/textInput/textInput.css.ts
  apps/user/src/components/common/textInput/textInput.test.tsx
  apps/user/src/components/sample/Counter.tsx
  apps/user/src/components/sample/TodoList.tsx
  apps/user/src/hooks/useAutoComplete.ts
  apps/user/src/stores/counter/counterStore.ts
  apps/user/src/stores/index.ts
  apps/user/src/styles/theme.css.ts
  apps/user/src/types/images.d.ts
  apps/user/tsconfig.json
  apps/user/vitest.config.mts
  pnpm-lock.yaml
Labels: Needs Review

#64 feat: 매장 상세 레이아웃
  apps/user/public/icons/btn_close_white.svg
  apps/user/public/icons/chevron_left.svg
  apps/user/public/icons/decrease.svg
  apps/user/public/icons/description.svg
  apps/user/public/icons/dropdown_off.svg
  apps/user/public/icons/dropdown_on.svg
  apps/user/public/icons/increase.svg
  apps/user/public/icons/review.svg
  apps/user/public/images/back_l.png
  apps/user/public/images/back_m.png
  apps/user/public/images/back_s.png
  apps/user/public/images/thumb.png
  apps/user/src/app/(topNav)/layout.tsx
  apps/user/src/app/(topNav)/store/[id]/page.tsx
  apps/user/src/app/(topNav)/store/[id]/storeDetail.css.ts
  apps/user/src/components/common/bottomSheet/bottomSheet.css.ts
  apps/user/src/components/common/bottomSheet/index.tsx
  apps/user/src/components/common/button/button.css.ts
  apps/user/src/components/common/statusLabel/index.tsx
  apps/user/src/components/ui/layout/bottomNav/index.tsx
  apps/user/src/components/ui/layout/topNav/index.tsx
  apps/user/src/components/ui/layout/topNav/topNav.css.ts
  apps/user/src/components/ui/storeDetail/productBottomSheet/index.tsx
  apps/user/src/components/ui/storeDetail/productBottomSheet/productBottomSheet.css.ts
  apps/user/src/components/ui/storeDetail/productSelector/index.tsx
  apps/user/src/components/ui/storeDetail/productSelector/productSelector.css.ts
  apps/user/src/components/ui/storeDetail/products/index.tsx
  apps/user/src/components/ui/storeDetail/products/products.css.ts
  apps/user/src/components/ui/storeDetail/select/index.tsx
  apps/user/src/components/ui/storeDetail/select/select.css.ts
  apps/user/src/components/ui/storeDetail/selectedItem/index.tsx
  apps/user/src/components/ui/storeDetail/selectedItem/selectedItem.css.ts
  apps/user/src/components/ui/storeDetail/storeInfo/index.tsx
  apps/user/src/components/ui/storeDetail/storeInfo/storeInfo.css.ts
  apps/user/src/components/ui/storeDetail/storeProduct/index.tsx
  apps/user/src/components/ui/storeDetail/storeProduct/storeProduct.css.ts
  apps/user/src/components/ui/storeDetail/totalPrice/index.tsx
  apps/user/src/components/ui/storeDetail/totalPrice/totalPrice.css.ts
  apps/user/src/constants/route.tsx
  apps/user/src/styles/global.css.ts
  apps/user/src/styles/reset.css.ts
  apps/user/src/styles/theme.css.ts
  apps/user/src/types/statusLabel.type.ts
  apps/user/src/utils/productStatus/index.ts
  biome.json
Labels: Needs Review

#67 feat: 매장 상세 모킹
  apps/user/.env.example
  apps/user/next.config.ts
  apps/user/src/apis/ssr/stores/index.ts
  apps/user/src/app/(topNav)/store/[id]/page.tsx
  apps/user/src/components/common/checkbox/index.tsx
  apps/user/src/components/common/products/index.tsx
  apps/user/src/components/common/products/product.test.tsx
  apps/user/src/components/common/products/products.css.ts
  apps/user/src/components/ui/storeDetail/productBottomSheet/index.tsx
  apps/user/src/components/ui/storeDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storeDetail/productSelector/index.tsx
  apps/user/src/components/ui/storeDetail/productSelector/productSelector.test.tsx
  apps/user/src/components/ui/storeDetail/products/index.tsx
  apps/user/src/components/ui/storeDetail/select/index.tsx
  apps/user/src/components/ui/storeDetail/select/select.css.ts
  apps/user/src/components/ui/storeDetail/select/select.test.tsx
  apps/user/src/components/ui/storeDetail/selectedItem/index.tsx
  apps/user/src/components/ui/storeDetail/selectedItem/selectedItem.test.tsx
  apps/user/src/components/ui/storeDetail/storeInfo/index.tsx
  apps/user/src/components/ui/storeDetail/storeProduct/index.tsx
  apps/user/src/components/ui/storeDetail/storeProducts/index.tsx
  apps/user/src/components/ui/storeDetail/storeProducts/storeProduct.css.ts
  apps/user/src/components/ui/storeDetail/totalPrice/index.tsx
  apps/user/src/hooks/api/usePostOrder/index.tsx
  apps/user/src/mocks/handlers/example/index.ts
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/mocks/handlers/orders/index.ts
  apps/user/src/mocks/handlers/stores/index.ts
  apps/user/src/mocks/utils.ts
  apps/user/src/types/apis/store.type.ts
  apps/user/src/utils/format/format.test.ts
  apps/user/src/utils/format/index.ts
Labels: Needs Review

#68 feat: 주문 상세
  apps/user/public/icons/place.svg
  apps/user/public/images/mockOrder.png
  apps/user/src/apis/ssr/orders/index.ts
  apps/user/src/app/(topNav)/orders/[id]/orders.css.ts
  apps/user/src/app/(topNav)/orders/[id]/page.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/common/orderInfo/orderInfo.css.ts
  apps/user/src/components/common/orderInfo/orderInfo.test.tsx
  apps/user/src/components/ui/layout/topNav/topNav.css.ts
  apps/user/src/components/ui/orders/reserve/index.tsx
  apps/user/src/mocks/handlers/orders/index.ts
  apps/user/src/types/apis/order.type.ts
  apps/user/src/utils/format/format.test.ts
  apps/user/src/utils/format/index.ts
Labels: Needs Review

#76 feat: 자동완성 기능 구현
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/components/ui/autoComplete/autoComplete.css.ts
  apps/user/src/components/ui/autoComplete/index.tsx
  apps/user/src/hooks/useAutoComplete.ts
  apps/user/src/hooks/useAutoComplete/index.ts
  apps/user/src/hooks/useAutoComplete/useAutoComplete.test.ts
  apps/user/src/hooks/useSearchRecommendations/index.ts
  apps/user/src/hooks/useSearchRecommendations/useSearchRecommendations.test.ts
  apps/user/src/mocks/handlers/recommendations/index.ts
  apps/user/src/stores/index.ts
  apps/user/src/stores/searchHistory/searchHistoryStore.ts
Labels: Needs Review

#73 chore: 폰트 및 글자 설정
  apps/user/src/app/fonts/PretendardVariable.woff2
  apps/user/src/app/layout.tsx
  apps/user/src/components/common/orderInfo/orderInfo.css.ts
  apps/user/src/components/ui/storeDetail/storeInfo/storeInfo.css.ts
  apps/user/src/components/ui/storeDetail/totalPrice/totalPrice.css.ts
  apps/user/src/styles/reset.css.ts
Labels: Needs Review

#75 feat: 주문 내역 확인
  apps/user/src/app/(topNav)/my-orders/[id]/page.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/common/orderInfo/orderInfo.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/actionButton.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/actionsButtons.css.ts
  apps/user/src/components/ui/my-orders/actionButtons/index.tsx
  apps/user/src/constants/my-orders/index.ts
  apps/user/src/constants/route/index.tsx
  apps/user/src/types/apis/order.type.ts
Labels: Needs Review

#78 refactor: store 코드 리팩토링
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/components/common/orderInfo/orderInfo.test.tsx
  apps/user/src/components/common/products/index.tsx
  apps/user/src/components/common/products/product.test.tsx
  apps/user/src/components/ui/storeDetail/productBottomSheet/index.tsx
  apps/user/src/components/ui/storeDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storeDetail/productSelector/productSelector.test.tsx
  apps/user/src/components/ui/storeDetail/select/index.tsx
  apps/user/src/components/ui/storeDetail/select/select.test.tsx
  apps/user/src/components/ui/storeDetail/selectedItem/index.tsx
  apps/user/src/components/ui/storeDetail/selectedItem/selectedItem.css.ts
  apps/user/src/components/ui/storeDetail/selectedItem/selectedItem.test.tsx
  apps/user/src/components/ui/storeDetail/totalPrice/index.tsx
  apps/user/src/hooks/useSelectedProducts/index.ts
  apps/user/src/hooks/useSelectedProducts/useSelectedProducts.test.ts
  apps/user/src/types/apis/store.type.ts
  apps/user/src/types/orders.type.ts
  biome.json
Labels: Needs Review

#79 refactor: store 경로 명칭 수정
  apps/user/src/apis/ssr/stores/index.ts
  apps/user/src/app/(topNav)/store/[id]/page.tsx
  apps/user/src/app/(topNav)/stores/[id]/page.tsx
  apps/user/src/app/(topNav)/stores/[id]/storesDetail.css.ts
  apps/user/src/components/common/products/index.tsx
  apps/user/src/components/common/products/product.test.tsx
  apps/user/src/components/ui/storeDetail/storeProducts/index.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/index.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.css.ts
  apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storesDetail/productSelector/index.tsx
  apps/user/src/components/ui/storesDetail/productSelector/productSelector.css.ts
  apps/user/src/components/ui/storesDetail/productSelector/productSelector.test.tsx
  apps/user/src/components/ui/storesDetail/select/index.tsx
  apps/user/src/components/ui/storesDetail/select/select.css.ts
  apps/user/src/components/ui/storesDetail/select/select.test.tsx
  apps/user/src/components/ui/storesDetail/selectedItem/index.tsx
  apps/user/src/components/ui/storesDetail/selectedItem/selectedItem.css.ts
  apps/user/src/components/ui/storesDetail/selectedItem/selectedItem.test.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/index.tsx
  apps/user/src/components/ui/storesDetail/storesInfo/storesInfo.css.ts
  apps/user/src/components/ui/storesDetail/storesProducts/index.tsx
  apps/user/src/components/ui/storesDetail/storesProducts/storesProduct.css.ts
  apps/user/src/components/ui/storesDetail/totalPrice/index.tsx
  apps/user/src/components/ui/storesDetail/totalPrice/totalPrice.css.ts
  apps/user/src/constants/route/index.tsx
  apps/user/src/hooks/useSelectedProducts/index.ts
  apps/user/src/hooks/useSelectedProducts/useSelectedProducts.test.ts
  apps/user/src/types/apis/order.type.ts
  apps/user/src/types/apis/stores.type.ts
  apps/user/src/types/orders.type.ts
Labels: Needs Review

#82 feat: 나의 주문 내역
  apps/user/public/images/thumb2.png
  apps/user/public/images/thumb3.png
  apps/user/public/images/thumb4.png
  apps/user/public/images/thumb6.png
  apps/user/src/app/(bottomNav)/my-orders/myOrders.css.ts
  apps/user/src/app/(bottomNav)/my-orders/page.tsx
  apps/user/src/app/(not-used)/common-ui/page.tsx
  apps/user/src/components/common/orderInfo/index.tsx
  apps/user/src/components/common/orderInfo/orderInfo.test.tsx
  apps/user/src/components/common/products/index.tsx
  apps/user/src/components/common/products/product.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/actionButton.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/index.tsx
  apps/user/src/components/ui/my-orders/orderItem/orderItem.css.ts
  apps/user/src/components/ui/my-orders/orderItem/orderItem.test.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storesDetail/productSelector/productSelector.test.tsx
  apps/user/src/components/ui/storesDetail/select/select.test.tsx
  apps/user/src/constants/my-orders/index.ts
  apps/user/src/hooks/api/useGetMyOrder/index.ts
  apps/user/src/hooks/api/usePostOrder/index.ts
  apps/user/src/hooks/api/usePostOrder/index.tsx
  apps/user/src/hooks/useSelectedProducts/useSelectedProducts.test.ts
  apps/user/src/mocks/handlers/orders/index.ts
  apps/user/src/styles/theme.css.ts
  apps/user/src/types/apis/order.type.ts
  apps/user/src/types/apis/stores.type.ts
  apps/user/src/utils/format/index.ts
  biome.json
Labels: Needs Review

#90 feat: msw stores search list
  apps/user/src/mocks/handlers/index.ts
  apps/user/src/mocks/handlers/search/store/index.ts
  apps/user/vitest.config.mts
Labels: Needs Review

#80 feat: 동네 인증
  apps/user/public/icons/favorite.svg
  apps/user/public/icons/my_marker.svg
  apps/user/public/icons/selected_store_marker.svg
  apps/user/public/icons/star.svg
  apps/user/public/icons/store_marker.svg
  apps/user/src/app/(bottomNav)/locations/search/page.css.ts
  apps/user/src/app/(bottomNav)/locations/search/page.tsx
  apps/user/src/app/(bottomNav)/locations/search/ui/StoreInfoCard.tsx
  apps/user/src/app/(topNav)/locations/my-location/page.tsx
  apps/user/src/components/common/kakaoMap/index.tsx
  apps/user/src/components/ui/locations/loadingMap/LoadingMap.css.ts
  apps/user/src/components/ui/locations/loadingMap/index.tsx
  apps/user/src/components/ui/locations/myLocation/index.tsx
  apps/user/src/components/ui/locations/myLocation/myLocation.css.ts
  apps/user/src/components/ui/locations/myLocation/myLocation.test.tsx
  apps/user/src/components/ui/locations/searchMap/index.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.css.ts
  apps/user/src/components/ui/locations/searchMap/searchMap.test.tsx
  apps/user/src/components/ui/locations/storeMapInfo/index.tsx
  apps/user/src/components/ui/locations/storeMapInfo/storeMapInfo.css.ts
  apps/user/src/constants/locations/index.ts
  apps/user/src/constants/route/index.tsx
  apps/user/src/hooks/useGeolocation/index.ts
  apps/user/src/hooks/useKakaoLoader/index.ts
  apps/user/src/mocks/handlers/search/location/index.ts
  apps/user/src/types/kakao.d.ts
  apps/user/src/utils/locations/locationUtils.test.tsx
  apps/user/src/utils/locations/locationUtils.ts
Labels: Needs Review

#89 chore: vitest 설정
  apps/owner/src/app/page.tsx
  apps/owner/src/components/sample/Counter.tsx
  apps/owner/src/components/sample/TodoList.tsx
  apps/owner/src/hooks/useTodos.ts
  apps/owner/src/stores/counter/counterStore.ts
  apps/owner/src/stores/index.ts
  apps/owner/test/setup.ts
  apps/owner/vitest.config.mts
  apps/user/src/app/orders/[id]/success/success.test.tsx
  apps/user/src/components/common/bottomSheet/bottomSheet.test.tsx
  apps/user/src/components/common/button/button.test.tsx
  apps/user/src/components/common/checkbox/checkbox.test.tsx
  apps/user/src/components/common/orderInfo/orderInfo.test.tsx
  apps/user/src/components/common/products/product.test.tsx
  apps/user/src/components/common/statusLabel/statusLabel.test.tsx
  apps/user/src/components/common/textInput/textInput.test.tsx
  apps/user/src/components/common/virtualScroll/virtualScroll.test.tsx
  apps/user/src/components/ui/layout/bottomNav/bottomNav.test.tsx
  apps/user/src/components/ui/locations/searchMap/searchMap.test.tsx
  apps/user/src/components/ui/my-orders/actionButtons/actionButton.test.tsx
  apps/user/src/components/ui/my-orders/orderItem/orderItem.test.tsx
  apps/user/src/components/ui/orders/reserve/reserve.test.tsx
  apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx
  apps/user/src/components/ui/storesDetail/productSelector/productSelector.test.tsx
  apps/user/src/components/ui/storesDetail/select/select.test.tsx
  apps/user/src/components/ui/storesDetail/selectedItem/selectedItem.test.tsx
  apps/user/src/hooks/useAutoComplete/useAutoComplete.test.ts
  apps/user/src/hooks/useSearchRecommendations/useSearchRecommendations.test.ts
  apps/user/src/hooks/useSelectedProducts/useSelectedProducts.test.ts
  apps/user/src/test/setup.ts
  apps/user/src/utils/format/format.test.ts
  apps/user/src/utils/locations/locationUtils.test.tsx
  apps/user/src/utils/virtualScroll/virtualScroll.test.ts
  apps/user/vitest.config.mts
  package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: Needs Review

#102 chore: 개발 환경 배포 수정
  .github/workflows/owner-ci-cd.yml
  .github/workflows/user-ci-cd.yml
Labels: Needs Review

#92 feat: 통합 login
  apps/owner/package.json
  apps/owner/public/icons/kakao_icon.svg
  apps/owner/public/images/character3.png
  apps/owner/public/images/logoTitle.png
  apps/owner/src/app/login/page.tsx
  apps/owner/src/components/login/index.tsx
  apps/owner/src/components/login/login.test.tsx
  apps/owner/src/test/setup.ts
  apps/owner/test/setup.ts
  apps/owner/tsconfig.json
  apps/user/package.json
  apps/user/public/icons/kakao_icon.svg
  apps/user/public/images/character3.png
  apps/user/public/images/logoTitle.png
  apps/user/src/app/(topNav)/login/page.tsx
  apps/user/src/components/ui/login/index.tsx
  apps/user/src/components/ui/login/login.css.ts
  apps/user/src/components/ui/login/login.test.tsx
  apps/user/src/constants/route/index.tsx
  apps/user/tsconfig.json
  packages/constants/login.ts
  packages/index.ts
  packages/types/login.ts
  pnpm-workspace.yaml
Labels: Needs Review

#108 chore: 테스트 커버리지 관련 액션 수정
  .github/workflows/owner-ci-cd.yml
  .github/workflows/user-ci-cd.yml
Labels: Needs Review

#103 chore: vercel msw 설정
  .github/workflows/user-ci-cd.yml
  apps/user/src/app/layout.tsx
  apps/user/src/providers/msw/index.tsx
Labels: Needs Review

#88 feat: 메인페이지 필터 작업
  .husky/pre-commit
  apps/user/package.json
  apps/user/public/clock.svg
  apps/user/public/icons/add.svg
  apps/user/public/icons/bookmark.svg
  apps/user/public/icons/clock.svg
  apps/user/public/icons/notice.svg
  apps/user/public/icons/pin.svg
  apps/user/public/icons/search.svg
  apps/user/public/icons/store.svg
  apps/user/src/app/(bottomNav)/layout.test.tsx
  apps/user/src/app/(bottomNav)/my-orders/page.test.tsx
  apps/user/src/app/(bottomNav)/page.css.ts
  apps/user/src/app/(bottomNav)/page.test.tsx
  apps/user/src/app/(bottomNav)/page.tsx
  apps/user/src/app/(bottomNav)/ui/filterTab/constant.ts
  apps/user/src/app/(bottomNav)/ui/filterTab/filterTab.css.ts
  apps/user/src/app/(bottomNav)/ui/filterTab/foodTypeFilter.tsx
  apps/user/src/app/(bottomNav)/ui/filterTab/index.tsx
  apps/user/src/app/(bottomNav)/ui/filterTab/pickUpTimeFilter.tsx
  apps/user/src/app/(bottomNav)/ui/filterTab/type.ts
  apps/user/src/app/(bottomNav)/ui/filterTab/utils.ts
  apps/user/src/app/(bottomNav)/ui/mainHeader/index.tsx
  apps/user/src/app/(bottomNav)/ui/mainHeader/locationFilter.tsx
  apps/user/src/app/(bottomNav)/ui/mainHeader/mainHeader.css.ts
  apps/user/src/app/(topNav)/layout.test.tsx
  apps/user/src/app/(topNav)/mypage/faq/page.test.tsx
  apps/user/src/app/(topNav)/search/page.css.ts
  apps/user/src/app/(topNav)/search/page.test.tsx
  apps/user/src/app/(topNav)/search/page.tsx
  apps/user/src/app/(topNav)/search/ui/searchInput/index.tsx
  apps/user/src/app/(topNav)/search/ui/searchInput/searchInput.css.ts
  apps/user/src/app/(topNav)/search/ui/searchResult/index.tsx
  apps/user/src/app/(topNav)/search/ui/searchResult/searchResult.css.ts
  apps/user/src/components/ui/layout/topNav/topNav.test.tsx
  apps/user/src/components/ui/notice/noticeItem/noticeItem.test.tsx
  apps/user/src/components/ui/storeList/storeCard/index.tsx
  apps/user/src/constants/route/index.tsx
  apps/user/src/hooks/useBottomSheet/index.ts
  apps/user/src/hooks/useBottomSheet/useBottomSheet.test.ts
  apps/user/src/providers/search/index.tsx
  apps/user/src/stores/index.test.ts
  apps/user/src/utils/format/index.ts
  pnpm-lock.yaml
Labels: Needs Review
